version: "3.9"
services:
  tkr-worldserver:
    build: .
    ports:
      - "2000:2000"
    volumes:
      - tkr_resources:/data
    environment:
      - IS_DOCKER=true
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_AUTH=
      - REDIS_INDEX=0
volumes:
  tkr_resources:
networks:
  default:
    name: redis